config/routes.rb
MokkaDevelopers::Application.routes.draw do
  devise_for :users

  root to: "topics#index"

  resources :topics do
    resources :replies, only: [:create, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :body
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :body, :title
  has_many :replies, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    @topic = Topic.find(params[:topic_id])
    @reply = @topic.replies.build(params[:reply])
    if @reply.save
      redirect_to @topic
      flash[:success] = "Your Reply Saved"
    else
      flash[:error] = "Some Problem saving reply"
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @reply = Reply.find(params[:id])

    if @reply.destroy
      redirect_to @topic
      flash[:success] = "Reply Deleted"
    else
      flash[:error] = "Error deleting reply"
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @replies = @topic.replies
    @reply = @topic.replies.new
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(params[:topic])
    if @topic.save
      flash[:success] = "Topic created"
      redirect_to topic_url(@topic)
    else
      flash[:error] = "Error creating topic"
      render "new"
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(params[:topic])
        flash[:success] = "Topic updated"
        redirect_to topic_url(@topic)
      else
        flash[:error] = "Error updating topic"
        render "edit" 
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      flash[:success] = "Topic Deleted"
      redirect_to topics_url
    else
      flash[:error] = "Error Deleting topic"
      render "edit"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_flash_msgs.html.erb
<div class="row">
  <div class="span2">&nbsp;</div>
  <div class="span8">
    <% flash.each do |name, msg| %>
      <% if name == :error %>
        <div class="alert alert-error">
      <% elsif name == :success %>
        <div class="alert alert-success">
      <% elsif name == :name %>
        <div class="alert alert-notice">
      <% else %>
        <div class="alert">
      <% end %>
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <%= msg %>
        </div>
    <% end %>
  </div>
  <div class="span2">&nbsp;</div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="muted credit">An attempt from <a href="http://atthy.com">Atthy Software</a> </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a href="/" class="brand">Mokka Developers</a>
      <ul class="nav pull-right">
        <li> <a href="#">Sign Out</a> </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mokka Developers | Tech Forum Chennai | Developers Forum Chennai</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrap">
    <%= render "layouts/header" %>
    <div class="container page_content">
      <%= render "layouts/flash_msgs" %>
      <%= yield %>
    </div>
    <div id="push"></div>
  </div>
  <%= render "layouts/footer" %>

</body>
</html>

app/views/topics/_form.html.erb
<%= simple_form_for(@topic,
      defaults: { input_html: { class: "span8" } }) do |f| %>
  <%= f.input :title %>
  <%= f.input :body, as: "text" %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/destroy.html.erb
<h1>Topics#destroy</h1>
<p>Find me in app/views/topics/destroy.html.erb</p>

app/views/topics/edit.html.erb
<h1>Edit topic</h1>
<%= render "topics/form" %>

app/views/topics/index.html.erb
<table class="table">
<% @topics.each do |topic| %>
  <tr>
    <td><%= link_to topic.title, topic_path(topic) %></td>
  </tr>
<% end %>
</table>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<%= render "topics/form" %>

app/views/topics/show.html.erb
<div class="row">
  <div class="span8">
    <h1><%= @topic.title %></h1>
  </div>
  <div class="span4">
    <%= link_to "<i class='icon icon-edit' title='edit'></i>".html_safe, edit_topic_path(@topic) %>
    <%= link_to "<i class='icon icon-trash' title='delete'></i>".html_safe, topic_path(@topic),
      method: "delete", confirm: "Permenantely delete topic?" %>
  </div>
</div>
<div class="row">
  <div class="span8">
    <%= @topic.body.html_safe %>
  </div>
</div>
<br />
<div class="row">
  <div class="span8 new_reply">
    <%= simple_form_for([@topic, @reply],
                       defaults: { label: false }) do |f| %>
      <%= f.input :body, as: :text,
        input_html: { rows: 2, placeholder: "Your reply here",
        class: "span8" } %>
      <%= f.submit "Reply", class: "btn btn-primary pull-right" %>
    <% end %>
  </div>
  <% @replies.each do |reply| %>
      <% next unless reply.body #To prevent empty reply from showing %>
      <div class="reply span8">
        <div class="dropdown reply_controls pull-right">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon icon-chevron-down"></i></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            <li> <%= link_to "<i class='icon icon-edit' title='Edit reply'></i> Edit reply".html_safe, "#" %> </li>
            <li> <%= link_to "<i class='icon icon-trash' title='Delete reply'></i> Delete reply".html_safe, topic_reply_path(@topic.id, reply.id), method: :delete, confirm: "Delete Reply?" %> </li>
          </ul>
        </div>
        <%= reply.body %>
      </div>
  <% end %>
</div>

app/views/topics/update.html.erb
<h1>Topics#update</h1>
<p>Find me in app/views/topics/update.html.erb</p>